In [1]:
import stanza
stanza.download("ru")

2021-12-28 05:40:23 INFO: Downloading default packages for language: ru (Russian)...
2021-12-28 05:40:25 INFO: File exists: C:\Users\veron\stanza_resources\ru\default.zip.
2021-12-28 05:40:30 INFO: Finished downloading models and saved to C:\Users\veron\stanza_resources.


In [2]:
import pandas as pd

In [4]:
nlp = stanza.Pipeline(lang='ru', processors='tokenize,lemma,pos')

2021-12-28 05:40:38 INFO: Loading these models for language: ru (Russian):
| Processor | Package   |
-------------------------
| tokenize  | syntagrus |
| pos       | syntagrus |
| lemma     | syntagrus |

2021-12-28 05:40:39 INFO: Use device: gpu
2021-12-28 05:40:39 INFO: Loading: tokenize
2021-12-28 05:40:42 INFO: Loading: pos
2021-12-28 05:40:42 INFO: Loading: lemma
2021-12-28 05:40:42 INFO: Done loading processors!


In [5]:
def preprocess(text, nlp=nlp):
    list_of_results = []
    doc = nlp(text)
    for sent in doc.sentences:
        for word in sent.words:
            list_of_results.append([sent.text, word.text, word.lemma, word.start_char, word.end_char])            
    return list_of_results

In [6]:
reviews = pd.read_csv('train_split_reviews.txt', sep='\t', header=None)

In [7]:
reviews

0                                                  1
0    25709  Были 1 февраля. Я второй раз, подруга - первый...
1    10099  Были в Дитае на прошлой неделе с подругой. Заш...
2     1105  Один из моих любимых ресторанов. С самого откр...
3     3647  Остались очень довольны. Хотим поблагодарить ш...
4    37070  приехали к друзьям в Питер из Москвы на Новый ...
..     ...                                                ...
208  10645  Заезжали поужинать с подругой пару недель наза...
209  12341  Ходила туда вчера. Интерьер необычный, привлек...
210  34196  Бронировали столик в прошлые выходные (30.08.1...
211  17475  Была вчера в этом ресторане!Поехала туда не це...
212  32859  20 октября отмечали день рождения нашей фирмы ...

[213 rows x 2 columns]

In [18]:
ids = reviews[0].values
text_reviews = reviews[1].values
ids_reviews = list(zip(ids, text_reviews))

In [23]:
pre_res = preprocess(i_r[1])

In [24]:
pre_res

[['20 октября отмечали день рождения нашей фирмы в ресторане Аллегро.',
  '20',
  '20',
  0,
  2],
 ['20 октября отмечали день рождения нашей фирмы в ресторане Аллегро.',
  'октября',
  'октябрь',
  3,
  10],
 ['20 октября отмечали день рождения нашей фирмы в ресторане Аллегро.',
  'отмечали',
  'отмечать',
  11,
  19],
 ['20 октября отмечали день рождения нашей фирмы в ресторане Аллегро.',
  'день',
  'день',
  20,
  24],
 ['20 октября отмечали день рождения нашей фирмы в ресторане Аллегро.',
  'рождения',
  'рождение',
  25,
  33],
 ['20 октября отмечали день рождения нашей фирмы в ресторане Аллегро.',
  'нашей',
  'наш',
  34,
  39],
 ['20 октября отмечали день рождения нашей фирмы в ресторане Аллегро.',
  'фирмы',
  'фирма',
  40,
  45],
 ['20 октября отмечали день рождения нашей фирмы в ресторане Аллегро.',
  'в',
  'в',
  46,
  47],
 ['20 октября отмечали день рождения нашей фирмы в ресторане Аллегро.',
  'ресторане',
  'ресторан',
  48,
  57],
 ['20 октября отмечали день рождени

In [19]:
from tqdm import tqdm
import numpy as np

In [28]:
result = []
for i_r in tqdm(ids_reviews):
    pre_res = preprocess(i_r[1])
    for res in pre_res:
        to_app = list(i_r)
        to_app.extend(res)
        result.append(to_app)

100%|███████████████████████████████████████████████████████| 213/213 [00:21<00:00,  9.79it/s]


In [29]:
result

[[25709,
  'Были 1 февраля. Я второй раз, подруга - первый. Приехали не поздно, часов в семь. Народу было очень мало. Порадовало, что угодила ресторанным вкусам спутницы. На входе девушки спросили о наших предпочтениях и проводили на второй этаж. Предварительно очень подробно рассказав обо всех прелестях данного заведения. Предложили выбрать столик. Мягкие диваны с россыпью подушек. Довольно приятная негромкая музыка и легкий полумрак. Почему-то нас обслуживало два официанта. Второй был приятен и учтив, и как оказалось на память знал составляющие всех блюд. Он же помог спутнице с выбором вина, а мне с коктейльным напитком, а их тут на любой вкус и цвет, как говориться. Медальоны из говядины с запеченным картофелем были прекрасны. В последнее время совсем отошла от рыбы и радуюсь, когда подают хорошо приготовленное мясо. Заказ принесли достаточно быстро. В зале постоянно находилось на обслуживании человека два, так что на зов являлись в течение минуты. Провели в ресторане часа два с лиш

In [30]:
t_res = np.array(result).T

In [34]:
t_res

array([['25709', '25709', '25709', ..., '32859', '32859', '32859'],
       ['Были 1 февраля. Я второй раз, подруга - первый. Приехали не поздно, часов в семь. Народу было очень мало. Порадовало, что угодила ресторанным вкусам спутницы. На входе девушки спросили о наших предпочтениях и проводили на второй этаж. Предварительно очень подробно рассказав обо всех прелестях данного заведения. Предложили выбрать столик. Мягкие диваны с россыпью подушек. Довольно приятная негромкая музыка и легкий полумрак. Почему-то нас обслуживало два официанта. Второй был приятен и учтив, и как оказалось на память знал составляющие всех блюд. Он же помог спутнице с выбором вина, а мне с коктейльным напитком, а их тут на любой вкус и цвет, как говориться. Медальоны из говядины с запеченным картофелем были прекрасны. В последнее время совсем отошла от рыбы и радуюсь, когда подают хорошо приготовленное мясо. Заказ принесли достаточно быстро. В зале постоянно находилось на обслуживании человека два, так что на 

In [38]:
columns=['text_id', 'sentence', 'word', 'lemma', 'start', 'end']

("columns=['text_id',",
 "'sentence',",
 "'word',",
 "'lemma',",
 "'start',",
 "'end']")

In [48]:
result[0]

[25709,
 'Были 1 февраля. Я второй раз, подруга - первый. Приехали не поздно, часов в семь. Народу было очень мало. Порадовало, что угодила ресторанным вкусам спутницы. На входе девушки спросили о наших предпочтениях и проводили на второй этаж. Предварительно очень подробно рассказав обо всех прелестях данного заведения. Предложили выбрать столик. Мягкие диваны с россыпью подушек. Довольно приятная негромкая музыка и легкий полумрак. Почему-то нас обслуживало два официанта. Второй был приятен и учтив, и как оказалось на память знал составляющие всех блюд. Он же помог спутнице с выбором вина, а мне с коктейльным напитком, а их тут на любой вкус и цвет, как говориться. Медальоны из говядины с запеченным картофелем были прекрасны. В последнее время совсем отошла от рыбы и радуюсь, когда подают хорошо приготовленное мясо. Заказ принесли достаточно быстро. В зале постоянно находилось на обслуживании человека два, так что на зов являлись в течение минуты. Провели в ресторане часа два с лишни

In [94]:
train_data = pd.DataFrame(result)
train_data[9070:9085]

0                                                  1  \
9070  280  Привез в этот ресторан друг - у него там была ...   
9071  280  Привез в этот ресторан друг - у него там была ...   
9072  280  Привез в этот ресторан друг - у него там была ...   
9073  280  Привез в этот ресторан друг - у него там была ...   
9074  280  Привез в этот ресторан друг - у него там была ...   
9075  280  Привез в этот ресторан друг - у него там была ...   
9076  280  Привез в этот ресторан друг - у него там была ...   
9077  280  Привез в этот ресторан друг - у него там была ...   
9078  280  Привез в этот ресторан друг - у него там была ...   
9079  280  Привез в этот ресторан друг - у него там была ...   
9080  280  Привез в этот ресторан друг - у него там была ...   
9081  280  Привез в этот ресторан друг - у него там была ...   
9082  280  Привез в этот ресторан друг - у него там была ...   
9083  280  Привез в этот ресторан друг - у него там была ...   
9084  280  Привез в этот ресторан друг - у него там была ...   

                                                      2           3  \
9070  Первое, что бросилось в глаза - вежливый персо...           в   
9071  Первое, что бросилось в глаза - вежливый персо...       глаза   
9072  Первое, что бросилось в глаза - вежливый персо...           -   
9073  Первое, что бросилось в глаза - вежливый персо...    вежливый   
9074  Первое, что бросилось в глаза - вежливый персо...    персонал   
9075  Первое, что бросилось в глаза - вежливый персо...           .   
9076  С улыбкой открыли дверь, предложили оставить п...           С   
9077  С улыбкой открыли дверь, предложили оставить п...     улыбкой   
9078  С улыбкой открыли дверь, предложили оставить п...     открыли   
9079  С улыбкой открыли дверь, предложили оставить п...       дверь   
9080  С улыбкой открыли дверь, предложили оставить п...           ,   
9081  С улыбкой открыли дверь, предложили оставить п...  предложили   
9082  С улыбкой открыли дверь, предложили оставить п...    оставить   
9083  С улыбкой открыли дверь, предложили оставить п...      пальто   
9084  С улыбкой открыли дверь, предложили оставить п...           ,   

               4    5    6  
9070           в  129  130  
9071        глаз  131  136  
9072           -  137  138  
9073    вежливый  139  147  
9074    персонал  148  156  
9075           .  156  157  
9076           с  158  159  
9077      улыбка  160  167  
9078     открыть  168  175  
9079       дверь  176  181  
9080           ,  181  182  
9081  предложить  183  193  
9082    оставить  194  202  
9083      пальто  203  209  
9084           ,  209  210

In [46]:
train_split_aspects = pd.read_csv('train_split_aspects.txt', sep='\t', header=None)
train_split_aspects

0         1                         2    3    4         5
0     30808     Whole                 ресторане   16   25   neutral
1     30808  Interior              первом этаже   43   55   neutral
2     30808     Whole     руководству ресторана  124  145  positive
3     30808   Service  обслуживающему персоналу  147  171  positive
4     30808   Service               сотрудникам  189  200  positive
...     ...       ...                       ...  ...  ...       ...
3568  16630   Service              обслуживание   85   97  positive
3569  16630      Food                       Еда   99  102  positive
3570  16630   Service                 персоналу  244  253  positive
3571  16630     Whole                  ресторан  294  302  positive
3572  16630     Whole                     место  315  320  positive

[3573 rows x 6 columns]

In [53]:
arr_train_split_aspects = np.array(train_split_aspects)

In [57]:
result[0]

[25709,
 'Были 1 февраля. Я второй раз, подруга - первый. Приехали не поздно, часов в семь. Народу было очень мало. Порадовало, что угодила ресторанным вкусам спутницы. На входе девушки спросили о наших предпочтениях и проводили на второй этаж. Предварительно очень подробно рассказав обо всех прелестях данного заведения. Предложили выбрать столик. Мягкие диваны с россыпью подушек. Довольно приятная негромкая музыка и легкий полумрак. Почему-то нас обслуживало два официанта. Второй был приятен и учтив, и как оказалось на память знал составляющие всех блюд. Он же помог спутнице с выбором вина, а мне с коктейльным напитком, а их тут на любой вкус и цвет, как говориться. Медальоны из говядины с запеченным картофелем были прекрасны. В последнее время совсем отошла от рыбы и радуюсь, когда подают хорошо приготовленное мясо. Заказ принесли достаточно быстро. В зале постоянно находилось на обслуживании человека два, так что на зов являлись в течение минуты. Провели в ресторане часа два с лишни

In [69]:
arr_train_split_aspects[0]

array([30808, 'Whole', 'ресторане', 16, 25, 'neutral'], dtype=object)

In [66]:
len(train_split_aspects)

3573

In [75]:
result[0]

[25709,
 'Были 1 февраля. Я второй раз, подруга - первый. Приехали не поздно, часов в семь. Народу было очень мало. Порадовало, что угодила ресторанным вкусам спутницы. На входе девушки спросили о наших предпочтениях и проводили на второй этаж. Предварительно очень подробно рассказав обо всех прелестях данного заведения. Предложили выбрать столик. Мягкие диваны с россыпью подушек. Довольно приятная негромкая музыка и легкий полумрак. Почему-то нас обслуживало два официанта. Второй был приятен и учтив, и как оказалось на память знал составляющие всех блюд. Он же помог спутнице с выбором вина, а мне с коктейльным напитком, а их тут на любой вкус и цвет, как говориться. Медальоны из говядины с запеченным картофелем были прекрасны. В последнее время совсем отошла от рыбы и радуюсь, когда подают хорошо приготовленное мясо. Заказ принесли достаточно быстро. В зале постоянно находилось на обслуживании человека два, так что на зов являлись в течение минуты. Провели в ресторане часа два с лишни

In [73]:
len(set([tuple(i) for i in arr_train_split_aspects]))

3573

In [90]:
#23369
[i for i in arr_train_split_aspects if int(i[0]) == 23369]

[array([23369, 'Whole', 'ресторанчике', 32, 44, 'neutral'], dtype=object),
 array([23369, 'Service', 'Встретили', 141, 150, 'positive'], dtype=object),
 array([23369, 'Interior', 'залы', 172, 176, 'neutral'], dtype=object),
 array([23369, 'Interior', 'веранде', 206, 213, 'neutral'], dtype=object),
 array([23369, 'Interior', 'обстановка', 235, 245, 'positive'],
       dtype=object),
 array([23369, 'Interior', 'Интерьер', 295, 303, 'both'], dtype=object),
 array([23369, 'Interior', 'музыка', 361, 367, 'positive'], dtype=object),
 array([23369, 'Service', 'официантом', 421, 431, 'positive'], dtype=object),
 array([23369, 'Service', 'обслуживал', 471, 481, 'positive'], dtype=object),
 array([23369, 'Food', 'блюдах', 545, 551, 'neutral'], dtype=object),
 array([23369, 'Food', 'блюд', 594, 598, 'neutral'], dtype=object),
 array([23369, 'Service', 'Заказ был выполнен', 599, 617, 'positive'],
       dtype=object),
 array([23369, 'Service', 'Заказ', 599, 604, 'positive'], dtype=object),
 array(

In [96]:
arr_train_split_aspects

array([[30808, 'Whole', 'ресторане', 16, 25, 'neutral'],
       [30808, 'Interior', 'первом этаже', 43, 55, 'neutral'],
       [30808, 'Whole', 'руководству ресторана', 124, 145, 'positive'],
       ...,
       [16630, 'Service', 'персоналу', 244, 253, 'positive'],
       [16630, 'Whole', 'ресторан', 294, 302, 'positive'],
       [16630, 'Whole', 'место', 315, 320, 'positive']], dtype=object)

In [95]:
[i for i in arr_train_split_aspects if int(i[0]) == 280]


[array([280, 'Whole', 'ресторан', 14, 22, 'neutral'], dtype=object),
 array([280, 'Service', 'персонал', 148, 156, 'positive'], dtype=object),
 array([280, 'Service', 'открыли', 168, 175, 'positive'], dtype=object),
 array([280, 'Service', 'открыли дверь', 168, 181, 'positive'],
       dtype=object),
 array([280, 'Service', 'предложили', 183, 193, 'positive'], dtype=object),
 array([280, 'Service', 'принесли меню', 218, 231, 'positive'],
       dtype=object),
 array([280, 'Service', 'принесли', 218, 226, 'positive'], dtype=object),
 array([280, 'Service', 'подошли', 247, 254, 'positive'], dtype=object),
 array([280, 'Interior', 'Интерьер', 342, 350, 'positive'], dtype=object),
 array([280, 'Interior', 'столики', 422, 429, 'positive'], dtype=object),
 array([280, 'Interior', 'места в центре ресторана', 449, 473, 'negative'],
       dtype=object),
 array([280, 'Service', 'Заказ принесли', 524, 538, 'positive'],
       dtype=object),
 array([280, 'Food', 'приготовлено', 554, 566, 'positiv

In [62]:
len(result)

35411

In [127]:
type_of_aspect = []
words = []
sentim_aspect = []
errs = 0
last_start_num = -1
last_end_num = 0
for s in tqdm(result):
    flag = 0
    for exam in arr_train_split_aspects:
        if s[0] == exam[0]:
            if (s[-2] >= exam[-3]) and (s[-1] <= exam[-2]):
                    flag = 1
                    type_of_aspect.append(exam[1])
                    sentim_aspect.append(exam[-1])
                    words.append(s[-4])
                    last_start_num = exam[-3]
                    last_end_num = exam[-2]
                    
    if flag == 0:
        type_of_aspect.append('O')
        sentim_aspect.append('O')
        words.append(s[-4])

100%|██████████████████████████████████████████████████| 35411/35411 [00:44<00:00, 796.15it/s]


In [ ]:
#5876
#9079
#9087
#28176
#34306

In [135]:
i = 34306
while words[i+5] == train_data[3][i]:
    i += 1
print(i)

IndexError: list index out of range

In [111]:
words[9075:9090]

['персонал',
 '.',
 'С',
 'улыбкой',
 'открыли',
 'открыли',
 'дверь',
 ',',
 'предложили',
 'оставить',
 'пальто',
 ',',
 'быстро',
 'принесли',
 'принесли']

In [88]:
train_data[3][9075:9090]

5870            свои
5871    рекомендации
5872    относительно
5873          выбора
5874           блюд.
5875           Заказ
5876             был
5877        выполнен
5878           очень
5879          быстро
Name: 3, dtype: object

In [85]:
i

5876

In [136]:
#5876
#9079
#9087
#28176
#34306
del type_of_aspect[5876]
del type_of_aspect[9079]
del type_of_aspect[9087]
del type_of_aspect[28176]
del type_of_aspect[34306]

del sentim_aspect[5876]
del sentim_aspect[9079]
del sentim_aspect[9087]
del sentim_aspect[28176]
del sentim_aspect[34306]

In [137]:
train_data['aspect'] = type_of_aspect
train_data['sentim'] = sentim_aspect

In [138]:
len(type_of_aspect)

35411

In [139]:
from collections import Counter
Counter(type_of_aspect)

Counter({'O': 30647,
         'Service': 1114,
         'Whole': 749,
         'Interior': 670,
         'Food': 2112,
         'Price': 119})

In [140]:
#3573
100 + 1429 + 511 + 610 + 907

3557

In [141]:
train_data[train_data[0]==30808][:50]

0                                                  1  \
15082  30808  Отмечали в этом ресторане день рождение на пер...   
15083  30808  Отмечали в этом ресторане день рождение на пер...   
15084  30808  Отмечали в этом ресторане день рождение на пер...   
15085  30808  Отмечали в этом ресторане день рождение на пер...   
15086  30808  Отмечали в этом ресторане день рождение на пер...   
15087  30808  Отмечали в этом ресторане день рождение на пер...   
15088  30808  Отмечали в этом ресторане день рождение на пер...   
15089  30808  Отмечали в этом ресторане день рождение на пер...   
15090  30808  Отмечали в этом ресторане день рождение на пер...   
15091  30808  Отмечали в этом ресторане день рождение на пер...   
15092  30808  Отмечали в этом ресторане день рождение на пер...   
15093  30808  Отмечали в этом ресторане день рождение на пер...   
15094  30808  Отмечали в этом ресторане день рождение на пер...   
15095  30808  Отмечали в этом ресторане день рождение на пер...   
15096  30808  Отмечали в этом ресторане день рождение на пер...   
15097  30808  Отмечали в этом ресторане день рождение на пер...   
15098  30808  Отмечали в этом ресторане день рождение на пер...   
15099  30808  Отмечали в этом ресторане день рождение на пер...   
15100  30808  Отмечали в этом ресторане день рождение на пер...   
15101  30808  Отмечали в этом ресторане день рождение на пер...   
15102  30808  Отмечали в этом ресторане день рождение на пер...   
15103  30808  Отмечали в этом ресторане день рождение на пер...   
15104  30808  Отмечали в этом ресторане день рождение на пер...   
15105  30808  Отмечали в этом ресторане день рождение на пер...   
15106  30808  Отмечали в этом ресторане день рождение на пер...   
15107  30808  Отмечали в этом ресторане день рождение на пер...   
15108  30808  Отмечали в этом ресторане день рождение на пер...   
15109  30808  Отмечали в этом ресторане день рождение на пер...   
15110  30808  Отмечали в этом ресторане день рождение на пер...   
15111  30808  Отмечали в этом ресторане день рождение на пер...   
15112  30808  Отмечали в этом ресторане день рождение на пер...   
15113  30808  Отмечали в этом ресторане день рождение на пер...   
15114  30808  Отмечали в этом ресторане день рождение на пер...   
15115  30808  Отмечали в этом ресторане день рождение на пер...   
15116  30808  Отмечали в этом ресторане день рождение на пер...   
15117  30808  Отмечали в этом ресторане день рождение на пер...   
15118  30808  Отмечали в этом ресторане день рождение на пер...   
15119  30808  Отмечали в этом ресторане день рождение на пер...   
15120  30808  Отмечали в этом ресторане день рождение на пер...   
15121  30808  Отмечали в этом ресторане день рождение на пер...   
15122  30808  Отмечали в этом ресторане день рождение на пер...   
15123  30808  Отмечали в этом ресторане день рождение на пер...   
15124  30808  Отмечали в этом ресторане день рождение на пер...   
15125  30808  Отмечали в этом ресторане день рождение на пер...   
15126  30808  Отмечали в этом ресторане день рождение на пер...   
15127  30808  Отмечали в этом ресторане день рождение на пер...   
15128  30808  Отмечали в этом ресторане день рождение на пер...   
15129  30808  Отмечали в этом ресторане день рождение на пер...   
15130  30808  Отмечали в этом ресторане день рождение на пер...   
15131  30808  Отмечали в этом ресторане день рождение на пер...   

                                                       2               3  \
15082  Отмечали в этом ресторане день рождение на пер...        Отмечали   
15083  Отмечали в этом ресторане день рождение на пер...               в   
15084  Отмечали в этом ресторане день рождение на пер...            этом   
15085  Отмечали в этом ресторане день рождение на пер...       ресторане   
15086  Отмечали в этом ресторане день рождение на пер...            день   
15087  Отмечали в этом ресторане день рождение на пер...        рождение   
15088  Отмечали в этом ресторане день рождение на пер...     

In [142]:
train_data.to_csv('train_data.csv')

In [126]:
(162 >= 147) and (171 <= 171)

True